title: Jaime Santos Rodríguez
description: Profesor Ayudante Doctor
logo: /photos/foto perfil.png
google_analytics: 
show_downloads: false
theme: jekyll-theme-minimal
markdown: kramdown
gems:
  - jekyll-mentions
  - jemoji
